---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 1440m
  url: https://github.com/alex1989hu/kubelet-serving-cert-approver
  ref:
    branch: main
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1440m
  url: https://github.com/kubernetes-sigs/metrics-server
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 1440m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: kubelet-serving-cert-approver
  path: ./deploy/standalone
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1440m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: metrics-server
  path: ./manifests/components/release
  prune: true
  wait: true
