---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 1440m
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.4.1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-standard
  namespace: flux-system
spec:
  interval: 1440m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: gateway-api
  path: ./config/crd
  prune: true
  wait: true
