apiVersion: v1
kind: Secret
metadata:
  name: tranga-pg-creds
  namespace: manga
stringData:
  password: ENC[AES256_GCM,data:3aGgTXUDCiy/7cGPOZjHh9AYHnAZtI0W8WRFj3+3SVNc3djAYDjO4frSvm4MQtZFp/z0U6yNWgnZVxK4NO42pA==,iv:ATZcau4ZbHz9Fe9Jfyq0fUSm86ststL0KVg1uQ9AUys=,tag:uLWr7rD7BmvCep0BcrAsww==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaHE5c2Yyb2c1WjFKMVds
        Ny9TSjJ5TGw5Q2dHcWZSWWQ4Q0lkVUxwTVFVCi9Kcmo1Sit0dXp0OEtHVm1ZQUs5
        WnZ0MFdyVmxkY1hEclRsN3dleUUwd1UKLS0tIEM4U0RadGZieThaeXVrU3loeHJD
        bXk4K2hZdHUxQ2IvSTVzVWlEN2dZajQK8+lu1Ig5TXBzolcIn22wYuTPedgB3VY6
        Jw6oBYLBuUOarkOI04I10jI42v8kYJhYexmR5XfRWzYiIHeYfMWhug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T23:53:32Z"
  mac: ENC[AES256_GCM,data:nu0bZgIANL+h3Nslh00956D5pXDO/4tuYLcRBASxhZMVtHGHfPFsx9KoLdUnr86p/qFnjXUdlYmdQXCXvSY5S8jx5g2qjdWtadIm3XXe8/nQEY/cQ+AveoTj5eFfsPug5YkLCFkbyESSJICi2LxyF2LNB7NxeG67idHEYYL6dHI=,iv:FUgfwly1LNdzNMPomzYwQZlrsRmDc7nRAurwsMmV14M=,tag:lNq/nNsrdX32E6fleF+yXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
