apiVersion: v1
kind: Secret
metadata:
    name: global-variables
    namespace: flux-system
stringData:
    mainDomain: ENC[AES256_GCM,data:0H8u611DFx8=,iv:qj/UczX3JebqdgMOxTlAP/ErcJTWcY7hyi1xK6b7jZk=,tag:tToZ+cCJ4fPe/p4nF0SmKw==,type:str]
    serviceDomain: ENC[AES256_GCM,data:6pUEIa8JYshjU+cHROHr7RnbupoMq7s1WLO0,iv:olNt9IoBHJuhmg+n1YLglCaJFt+lIGO6ZukSfY2RuGQ=,tag:elWLZS3lye0YIfPlaAAt6g==,type:str]
    nasIp: ENC[AES256_GCM,data:VuWOIAMcrEx5+t8Pjg==,iv:+p34XqVQAdoTe1mRJvdmnZDcQNvhmqUzHdbJgE6TyXs=,tag:VqdLWXm2mnnA0F/2LEpKRg==,type:str]
    nasNfsPath: ENC[AES256_GCM,data:pO+GlccozO8=,iv:fwszXZWuLvISUD4dJlmLTodiNpCyGRNRtnSUsJ5oJqY=,tag:OMXE2jMrNPAWO+5o3NecYQ==,type:str]
    userId: ENC[AES256_GCM,data:ZmXon14=,iv:3ESrO1TGZfQSoOf0UJpDMpjyKpVqtizbxbQsOquTDNE=,tag:v18gjcAjOE+Ms6SapImXSQ==,type:str]
    groupId: ENC[AES256_GCM,data:MO0HNIc=,iv:74WMzmcmKbY596xNddBGcGBATVfOfnONq3g/+SXIyNY=,tag:SBGSvHX19vYLL1UsQIV3gA==,type:str]
    timezone: ENC[AES256_GCM,data:9PpxXQ/5U0uhojKp3xji,iv:7ZZVS7RzvqdVzHqyS2oQDFrpCBgeBP5RMf5ql0I6XUY=,tag:+YvhN374i0r/P5i4GEd5CA==,type:str]
sops:
    age:
        - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ0RKS3NldlgzdUJBdkVq
            S01HWWNTZVRNbVFDRElzelg5dCtiU0MvTWpRClVvdlVCV0gxWXp1eHdDaGpoeEpi
            cC93TysrUkdoV052aEJaR2s0MGthOFkKLS0tIDU5V3VPS0RCdVR3SFdzY2pjVVFx
            WldtNFVua1oxSGVYVUZhdTFKd09YeDQKPRdyxqTs2nAtziEEaxh4ggAVia5UKUeQ
            wRwnpZN5B7Zs9dj28BzILiiu5NiKonj1QoPe3Sl/38mltB9Tdw2Kjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T23:43:00Z"
    mac: ENC[AES256_GCM,data:NFbyoSCmJDzhV1beYa0XQfnptEFY3dg5Rf2nWW5pkuQrKPfpRCNSNC0o1qnlPng0jREBr0MzIg90m2ZxvODvc9ilTqsLt/bEnlFa9JtS6MpiePF4HJ0CDE5cKow/eAmKcBxQyeUUQX3k1qccsqW7AstksPl2mp19fJR2J04yFOU=,iv:V726f+IBgnfny6JEP3yTnw38+pBoShpvOGUSlS97goY=,tag:QDK3xZyVWb6KB2vRUH4srg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
