apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret-values
  namespace: flux-system
stringData:
  harborPassword: ENC[AES256_GCM,data:0/4FX9wHGyepsjD1G2iJ,iv:hQCMeVA05UAuk9hr1LKqcSUkgYblhZVB5IBtbcnHeK4=,tag:+uiuCEDGYh3J+t/Feoxw1g==,type:str]
  harborPgPassword: ENC[AES256_GCM,data:M9tHbWvoV7dxZjkYQ/lWjC3bv5/MYi7lgtnFOkJEIc7sTi87qdEMFI6h/wvxBWbllV8k1EV41Zhq8IRyg8LtXg==,iv:dzLQUBQxU8Jx4/atdWUBIqaAwpsjWwLjA4ARmxSwZxU=,tag:z01PVsrl+2xjuynoS18K3w==,type:str]
  harborValkeyPassword: ENC[AES256_GCM,data:Qx82+nxQhMU8Ky3UZbPtCGDAEgQm2vjZ1VMtMxK3WE/o4wBsEZS7it67HNuAF/qUpULOe5TUYO+rdht7GxLb6A==,iv:2vsdZBS3lwFTj8pF1ejMYmfrITyvmqF63MbcVP6CpVc=,tag:wPgecKXX0TrfWbP5CEyMMw==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMWx2bGx5aHU4b2FoVmtw
        WXpPSk1ERFlNZFYxcmhkNHBITlpjMXZYamdRCmxncTlhUTBnMW41Ry8yYzUrNE5U
        QSt2OTJkTm5wQ0k2eU1MbnlpK3IycjAKLS0tIHdocExRbEpWUVlUcE1aWHN1bVA3
        Z3RHTXJhSnZSemZ4aXg3YU1mdXR5V1UKMSCMZU5z4ivc47lkDkRRIYngEDdVP/9n
        Ulw56YBMJDwrWc7AVSFTxuYmutlpSS7LUdDuGYEvvjXYKwPsA8hnJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T18:52:30Z"
  mac: ENC[AES256_GCM,data:Bk5GyulXGfXwg4ySncSQxqnC6H3mpPjjHxoYVPO+R3PwY7UDFBj0oSxOB9vRHiFdW2vO+Z3K7YQ+pSYIIEoLreZO8xmBpZsWnh11NJTbo4xRNx7xf0G43D2RPcSkjySblgO0bnPTDIYQVankdJNaugLdgX1f49jeys1LpLwI9hY=,iv:ZBlAGjNgMrZQIQn/RyuGI44125yB2ADDv0IEhqvQUMw=,tag:8bHCi5ZIw2jlysH8vcemOA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
