---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-base
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/base
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/template/spec/containers/0/args
          value:
            - --device
            - |
              name: video
              groups:
                - paths:
                    - path: /dev/video0
                  count: 50
            - --device
            - |
              name: hwa
              groups:
                - paths:
                  - path: /dev/dri
                  count: 50
            - --device
            - |
              name: tun
              groups:
                - count: 1000
                  paths:
                    - path: /dev/net/tun
      target:
        kind: DaemonSet
        name: generic-device-plugin
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-k8s00
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/k8s00
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: external-dns-values
