apiVersion: v1
kind: Secret
metadata:
  name: cf-tunnel-token
  namespace: immich
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:KSU6TezpjYbIKU4CEPq9Af4k0sxkvSluyVGsVoyLhgYW2LlhXqBIPvGHCZiBduGyEivCX1N1lvve5nmD7ALjeAFcOgxBQ4s+cT2x605RmqE2+GUhxetuouuPsxqrbVVOud6YXF1Qy6OzItDjqM/SQJ7CjMdsFgf51dFWARV9MNzcmgI/7tBUR3j5MAeJPCtlR8pkL/3kGXJ6Iv+3sMGMKqq2hsAceeRHZUeTY5eCEfQmeleADDNJgl5BYVDeMOTJUM5rZPuS9l1Al0NG70zhhWPNeoHBdqanlGyBft59P5qFG1EbeURY6XDV99hb/9Hk,iv:/HC6NDNQKWuzrCurhySg/kFg9d4VyJtxBSf6pOJ32dk=,tag:eqz/MMfZD0h85CL8NH4DMQ==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aE1GbjEwT3p6clYvZm80
        UythTXgzbisxUmY0N1FEM2w0R3E2OXlYQ3lrCjJzQksrdE9DR3o3dEFQTU9NZUV4
        cFlGd1dXMWVCNWswajhLVVAwbkg3L3cKLS0tIEp3Q21idXprdEZoYjRiUHlPaG8v
        akhUYVJnSEtuRncrZk1McHlFaFlNQzQK7TXfr5TDjM/T7pBwO6oC1EHAst8Uw8CT
        r7ak4LLZ8NVPOW5MhBQlkeNB+4+nDMB5Yy8RNliEZmvjOwDpUshomQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T13:11:02Z"
  mac: ENC[AES256_GCM,data:LtFXlolyaHRvXORLVdPqqakG1pbUj4ACp2gGtIR7l2HVzSAk53EE/DqrcL3xkhQuQgNcnIy97ViYt4goPzxXYf6L5bDQYqsrnALnvdkWpVgWRabmRGmxO5nCm5kb8nUJzPwBYJYAC4YbtxLTmcRojhSF2adR7AWAMGU8jKF+MP0=,iv:3wYtE30o6N4VgxNUIFgS7Da1q55yCqXsv+5S+CMFj4E=,tag:wVsBwyi7ROBMUM2aQUQ8aA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
