apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-credentials
  namespace: immich
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:Tmiw+lU2,iv:DQeu7k+CYWvz1bdH2GcmK4icD8edTChbvnFy8pd1OE4=,tag:2m+OndpQyzOZQc4k3obLbw==,type:str]
  password: ENC[AES256_GCM,data:2pbyP3xSpY1l2R7XuDR8Z7ZZ7fbc1xMd4hPfxwLXcKPb7uhIzMaK7NvvMkdUpDxIIVqeA2PahsfIWYPQDDeC4Q==,iv:krXZQYrMpNsVGb3xbCMyYoY6b0mYV7/dQ68k+R7ny0M=,tag:CfQAB0g0bP50shZ0lP/qWw==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbmVudjMvN1ZLc20xMGdU
        Z3hMRVhLMmVGalVGVm1CRUxnVC92QVRmR2lVCkc4WDdRUkFERjJCYjEwS2xvVHg1
        QUlEbURKaUxlQTFrcjBBblFtVTU2RE0KLS0tIDllUURpTHdQcWZlYUhjWi9oTjhY
        Qk5yaENuNHFKNmJpVW9UN2xJWFFJeGMKFKJfsnJA2cnXnZkI0/kL2Py92WiXtR3g
        uScXlUGYHMfRDCSl9UAbsQwyn2mxzJFpivWxcyrYSj+H2ILyQCxf3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T13:11:15Z"
  mac: ENC[AES256_GCM,data:Q3qMlq5frrv1MupIYU4jR1LfUKm2CUtKSYVZvgU7VPbzApmJm9vrKj570TBjTpFS4BghBCtmEo7x+SZ5Q+SufrVUPW10pKF85NuqJQs21xRPws+DCawGyh+XmHy9/BgZ240EhWcEpm8UYWj4LgEplExFfzcmcKrJlf6V5wayQLY=,iv:gIrN6DGIClpGJpID6R3z0VfyDyNZujP8n1YlBVjJwMo=,tag:osKJV3cnbdBdd4bRa4dOnA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
