apiVersion: v1
kind: Secret
metadata:
  name: immich
  namespace: immich
type: Opaque
stringData:
  redis_password: ENC[AES256_GCM,data:o9jmso5E0jsggYV3T0zWE9ySPzbB8U8ens/1E9/rIXvnwA74L/7FMeVy4Q2gt+DGABhaNJ214icB6nGkjpBibg==,iv:+2jNQ6Al7MdpUN0iVbTTVCO4Lgspo6C4aaGIWkzbDKY=,tag:SAB2calgtOaD4OLZ5eTFNA==,type:str]
  pg_password: ENC[AES256_GCM,data:FKOIQb0azF77vsxGHfXPQe1DMEM57YBY2CXcKzDVrMA19ZcRZrUb0DRiNEm/svRlDBc4I0XT6pi1dfO6Cp9ZMA==,iv:SlRz+2jJu/rG59f2Wi56mCJBCskuBKBe0YMci3l64TY=,tag:FYdto7Nhda9sYxVHlFURww==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQS1Y0aE9ZZk9mQ2xMQ2pt
        ejNQditVRnVabnlicDIwMjRxVkxYNzNYcGtVClF0dWxmVnhIL0F0a240UzFSc09s
        L0dIT3Z1WjQvUWVDYkdsRjR5anFXbm8KLS0tIFdxTk5Fd2lIK1ZTbXo5UUVaM1Rq
        UEFTRWdkTWFvUVFHWVVxWHg1bVFXeEEK8Q+KzEA4OYyw8d6+SkWe2XiE2JUFo7I8
        qT/OyY1ak4E2A09DZekJ8o3TBoN8koKO8PBx191SdsDY4oVGulrpvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T13:11:21Z"
  mac: ENC[AES256_GCM,data:IrR31rjExGPuR6BwiqiiLvoe3Rk1AmXzm6hof01pHGLYN9LMoRxeU6fu7YhTlySyUF4afxxksoAoNQgws2u4nfeZavofXT1dH/DUJGT0l36HUxs3XV0OQ98VA23r3Xyx+oV/o7lKg8daKusZZs+lf6vorcfBtJiHlBvBwVUlzQQ=,iv:j73NfK/fa6PJGtUcl0ci1u1RevhByqyphhTNV17xuEU=,tag:lHp0AjO5C7zDbGiUZcT79g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
