apiVersion: v1
kind: Secret
metadata:
  name: cnpg-immich-pg-backup-creds
  namespace: immich
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:IPDa0psJJnf9bTgi/S0tgZitXtMz+TqOe/4=,iv:hEztNDUDcWMUh16pwBg+zuZifY1buFGoFHbCGndfk4o=,tag:zCOhRtGLkN2Tc/cR4pwDdQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:WpC8Vh7arwFI4VnSJzPriP6R2YRB3DSda+JksZp06Nk+H8hT9v8CFltZkEPjCOqqKVTKNvixB6dtQCCdU+ecEw==,iv:YNJiVxdRxElD5Tt8RIm2PGVDKLHvyfx7UXYJtA2lFyc=,tag:agAqI+2IC7PeTqr6kaGtVA==,type:str]
  region: ENC[AES256_GCM,data:9WtxkgCF,iv:hjW5hpRl8dN7VdSn51NR1p4hBDHZR08TMxHX9OmXaQo=,tag:9pO4xk5VlA7QqpGMW4SgVA==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeXdjVDNSRnA5ejVBOG5V
        REV5SUwvSjZxWlVxTzlSS3FoM05CSFo1OVZnCmo5a0JjM2l4YkYwMlRJTkh5NkZp
        VXlFV2FnNnh1VEllc3l5VGRJSzhXVjgKLS0tIEtSNmhWK29kdmdienM2SURlRm9V
        eS9SbVBZdFBGeWNaOElhWFB5RS92SkkKUWqTctfpA7tYY7NaUw7L5tIJE2N9ssGM
        ZVt4oXXPMCvXEyAsiUqNWF8PzNF+RyDX+AVXIBg2dleO6y0i7ChPNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T13:11:30Z"
  mac: ENC[AES256_GCM,data:uy3Lw6zSkwzKCXPR9N4YIbu5OM0e2xD8BMFtd0AJ3q2sSqNR+6FCBpI8LpDo041587B00NTXbcbvQbFeKm1thLYlXyXSSLQSNczld//TkfSS0Ts36OIPNRwjcqxRQF2PbpRH6k5mup+BO4Sz8ETSU7LDv9+QbpJHOnCaOqzOH9s=,iv:PjIRDBzrF8I7JuFNst/psle2DTBH1v/2l50DM4JtKHI=,tag:vjXgJ/rydjoC3HHV/7TEGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
