---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-valkey
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: valkey
      version: ">= 0.9.2 < 0.10"
      sourceRef:
        kind: HelmRepository
        name: valkey
        namespace: flux-system
      interval: 1m
  values:
    auth:
      enabled: true
      aclUsers:
        default:
          permissions: "~* &* +@all"
        immich:
          permissions: "~* &* +@all"
      usersExistingSecret: immich-valkey-users
    dataStorage:
      enabled: true
      className: rook-ceph-delete
      requestedSize: 5Gi
    metrics:
      enabled: true
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: false
      serviceMonitor:
        enabled: true
    replica:
      enabled: true
      replicas: 3
      replicationUser: default
      minReplicasToWrite: 1
      minReplicasMaxLag: 10
      service:
        enabled: true
      persistence:
        size: 5Gi
        storageClass: rook-ceph-delete
