apiVersion: v1
kind: Secret
metadata:
  name: immich-valkey-users
  namespace: immich
type: Opaque
stringData:
  default: ENC[AES256_GCM,data:v+qcboqpdK+BY3yq9Ql7RqptONnmEcINupfbM2MJojcfNiz2/ISq/1s7CQCD0CybvEgoku3wPUvQV8Ab8rcZaw==,iv:rOKBGiFX/8WeYJUR4QO/vKy+Zoc+E4EzlRKFmA9nbK4=,tag:BgQQFLkVgZ7dbFzEFIJNQQ==,type:str]
  immich: ENC[AES256_GCM,data:lDUcBB4RVjwe71cS4+MHme+NTbGIJ7y5h84QyXpAOsL36+f/+ztobemAF/9Y62N82kuTkkpVtHhtwJl12D2IiA==,iv:sTkdsv0fEg2JxnNylpOgrRC4gbe5U65TL95fCIQg/Io=,tag:FjnGwUh7U8DJ6ZuGTL/rfw==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RDByRlIwQmQrSG5BNGMy
        b0t4dXQzeW5CTWQvS1ppaFRpcXFUUWFNcnhBCnRobGh0R1Ntb3lzQWZ4Qit5VjQv
        eG1ZbHVDM1hzQ044WFVIT2Y5TVNJMTAKLS0tIFM3eEhxbVA2aEF4emJMWFowZDls
        QTRZdlkrQUdwNEhqSThMdzViU1EyNFEKgTw8T0XnL7mXRABI+AAVqgUhrEMuF0N+
        w8ExwA0I2mrCstujKaPG9yZEQev5lKwOzipXZIsT8hlP3InWqfBa1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T13:11:37Z"
  mac: ENC[AES256_GCM,data:hPaiVY84/ZvS6pBUmT3y+ylPHWKPeA7oCuAgIgFAzwS/nn/ez4NuhpKSaIGWxgQ6FaPGHBZpEXrqLAst5VXjySqkse1fnNLqOdcry1vACiy3ywkqVyH2C2d5VfUsRP0sFoKl06kwwmxIdpR4xtjs4slVAzQQQQCdAPEUQNnhcnw=,iv:A4/yvhi+too/qEdiIYZTlEUUjNFwjtLGs9Ffqq2pkW4=,tag:322kKtopXNC2aKef5aBsHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
