---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: plugin-barman-cloud
      version: ">=0.5.0 <0.6.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: database
      interval: 1m
