apiVersion: v1
kind: Secret
metadata:
    name: cnpg-pg00-backup-creds
    namespace: database
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:QR1+40tCl9Mmcgl0y1pIgFG6Ecydg/cwIEQ=,iv:Y5p8+vPbTCz5QyEQJnmnL65eu4SPq69b/8kXnNpW9BU=,tag:O7fBGuv81dlm4A8KKTWl3A==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:4R0W+ZJXSiIKS8eMvfNtnGDRT1dXemMfs+mXzd0jcwjATPL22aD+MS3m8KrkLWHEkpXJ4NNJt1mZ+xbJPDiEDQ==,iv:zNh4ENx0TWOiiFFhkDBCV/lXYuePryiTlYRW+lVQpVs=,tag:eH49Q7C/qLCRTahyJGXxqA==,type:str]
    region: ENC[AES256_GCM,data:zZ8aaRrZ,iv:RGNm6syGOSGq7eaAM+zZKubkYyp6kCSMYZUAg0sZjM0=,tag:htyG3cte75mHVfea5guhXg==,type:str]
    superuserSecret: ENC[AES256_GCM,data:HOBY8hPUf7v7oGG/C1Q3x1ROlaCZdidJKO+qcrR9+IpIQLrti+RklqUTYwiZ2Tdd+tHfTTtwUktMGCX4JqcKzA==,iv:aVLD7W+gYVUM3/jJdYKKKqzs0l8Ns+r8JOeVcK1pO0g=,tag:6q4zDy0zl2mZaALzRpsQqw==,type:str]
sops:
    age:
        - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaTVlbDUxeUpxVlQ5dTJq
            Y011Mk93dGR2MGthWDFlR0RsSi82RlYxbkdnCjJOa0VYUnZET2lCeDBSS1BNQUk5
            aHlrLzZvamdVS1NpZDBVNm95RjNRTWMKLS0tIHhsWkdrVnZjdTVNVTJMT2xOcDla
            OVhXZmFTcmlDcXhIMnl3KzVOYTltWVUKbmp8vMOCtj+ntMY9mo1Eek2vDTBneLe1
            N7XUHpoinfTPIE+VovjkAlQ5PoT7VnsJ8L6ryvf3MBxe43qvv4MZCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T02:22:07Z"
    mac: ENC[AES256_GCM,data:VwiWPxrGpMAqFtglfsbmAbyzOpP5IsVU+JfCNxwDBhlurgzXYXE05+3bg+zKiTkPfdIaK3+hlJg1wwVURKjhJswMBLPG8HzRLeW1iya2l3I4CpbR9W4QrGV5DfTHFxsZoWrj8cRo2zB65U4jzAj4lOoaK6t+bDPSHvox8nF83Eg=,iv:lmlQyu8Q+jIIB1Da6D82oM4WLKdS5ZFCljlyf/RypCM=,tag:yeHKFtLjHYa+0t6TJlCoog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
