apiVersion: v1
kind: Secret
metadata:
  name: cnpg-pg00-backup-creds
  namespace: database
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:3gqLbb5xQqQ8F1MH6Loy6f/6i44TizV9HCQ=,iv:OKNwcJNL4RVK/ijN4waBEg5+dJc5HrwUC1TA+RvQD3o=,tag:c7xfIWnHADbu+Cso8rXiUQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:h+/+BcYpdiKFIBPi7MrNj5hdZ3KHCTEEQLy/2D5vUUMOfHzr1r+skmWyYbyfB4FCNmTvkFZdyMWzGccgJKNbJw==,iv:2yHz77rFGCMaDD8Ly7DFi2z9Dety2RPeFSqHQrs3/0E=,tag:LZan0TCHc6eYKy/oRM/T5w==,type:str]
  region: ENC[AES256_GCM,data:zZ8aaRrZ,iv:RGNm6syGOSGq7eaAM+zZKubkYyp6kCSMYZUAg0sZjM0=,tag:htyG3cte75mHVfea5guhXg==,type:str]
  superuserSecret: ENC[AES256_GCM,data:HOBY8hPUf7v7oGG/C1Q3x1ROlaCZdidJKO+qcrR9+IpIQLrti+RklqUTYwiZ2Tdd+tHfTTtwUktMGCX4JqcKzA==,iv:aVLD7W+gYVUM3/jJdYKKKqzs0l8Ns+r8JOeVcK1pO0g=,tag:6q4zDy0zl2mZaALzRpsQqw==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaTVlbDUxeUpxVlQ5dTJq
        Y011Mk93dGR2MGthWDFlR0RsSi82RlYxbkdnCjJOa0VYUnZET2lCeDBSS1BNQUk5
        aHlrLzZvamdVS1NpZDBVNm95RjNRTWMKLS0tIHhsWkdrVnZjdTVNVTJMT2xOcDla
        OVhXZmFTcmlDcXhIMnl3KzVOYTltWVUKbmp8vMOCtj+ntMY9mo1Eek2vDTBneLe1
        N7XUHpoinfTPIE+VovjkAlQ5PoT7VnsJ8L6ryvf3MBxe43qvv4MZCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T01:49:14Z"
  mac: ENC[AES256_GCM,data:ZZ5uEg+K/EPJH44Yhs1ppiPSRpoLtNgAfwl+tX6VRC7jacUR9A6MtqrOOun1xjk0SUuNw1+WPZ4Jr92xzaUoLLby1kQ/M0ZYVOwN/aYCR58DB+9EcaRnpCmTOLISoQeDTjM3/+BZJI8FVv5QHKFBVAMnDXiq5DQ5blFatt2/5ZU=,iv:9vwhWV/WfvLP4Exc0eKv1HJ+EPPl81mQ60Z5582pmaU=,tag:60+cTr19jbV0q5pnxdPgBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
