apiVersion: v1
kind: Secret
metadata:
  name: cnpg-pg00-super-user-creds
  namespace: database
stringData:
  username: ENC[AES256_GCM,data:i8v3jD+GKfw=,iv:gxzW+VveOIZnzOzP9JdE1LpxXdpieYfyPqNzQ9unHfI=,tag:hu+Ly3CRXwBo0qaWPBCVnQ==,type:str]
  password: ENC[AES256_GCM,data:0s6eopmgUtN+HGv/12NYA0SfPZtljeAFh67czvU39z1EaeYEjWLYBwZNG2Hd5It1nTi6huRv9UmYKB6Zy3Qmvw==,iv:+aYeG+0KKT+wfYLeBu3lw5x5HnyJOl/QHTTlu9BPl8g=,tag:LzfXsG7nq/EumLzDg0wiHw==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUzBiVVdPRW10d0ZKZ01u
        NHU4dTNiYmpENXBkci9oRHVDc0hXdTMvY2hzCnNEdlRDNThWWWZjSjBQaTM5c2px
        SGVDY0ZUejQzRWNhVmczNlBMMUo0cFUKLS0tIEhmVWtaTnpBMGQwa1VJRkVkS3pC
        VS8rMXh5OGJaZi9HVXdlSlVDb2pkaXMKkljjoOfDYyWPreZmLw5rL29e6MI6oRoA
        nAbs1VvEsZoOvyK/h9v6SbeT3GBL1yRdPp29qwmqPmRIC1S/QV5KJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T01:50:10Z"
  mac: ENC[AES256_GCM,data:TcMlx7vol9gNGrQ0PL85fl3HzkwJ65F3f1ngdIqvRrDmW5ZU+fIYiQ+O57JjHIeFkBS1ziSiAaEl0ABvJoeAMCGJjDrKBQ92iDjbK/+NbzpinAnJm/ji9ZzvJkvnEnOUtWXjyBJxoNvZBtAXeBhUmStNd2TkujoM+J81LHAavkk=,iv:Nkk9GSW5Djj8hCA/ADJQ/debnVkHihnloa+MSNmOxWM=,tag:ecVQk8nFp5dMX0f71RVaew==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
