apiVersion: v1
kind: Secret
metadata:
  name: kaizoku-postgres-credentials
  namespace: database
stringData:
  username: ENC[AES256_GCM,data:qz6LIrAGSA==,iv:UrC04J9uQNCvNfu7YDHqZoABB9nFnOe4geynRXkT92I=,tag:xbj/9diQ7O4rlTAilThQPg==,type:str]
  password: ENC[AES256_GCM,data:ar0Y9m1Ks5yckaE41Lg5uh6NXoXGZUgK6jpYjj8t2YtprYOMRuHGL+HnpI7qyNoQFZdWDUBncXO5fDqy1IS9Zg==,iv:i25cPI20jWsH0EBA/Q4GNJdHk5qxjX+NPdcpKBl2NZ0=,tag:TlmxIgktJ7frOAHKvSOdXA==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ1FCVzVDNEo1eWVBaTNP
        VjdYV1BSNnAyWmR6T2JTcDhnUzBtc0N5VHhNClBhSnhIc3RLb3VKbUJqeTN1aW9v
        eC9jUDZnN09veUVIeWc2NlVaVlN6MzAKLS0tIGxycStSRlIva2wzd2daNWtzSXRN
        WmNHOEdrUUpSMFY3T0VNU1oxNldjME0KbZNTK6bSrN4kTqkCxNOUcysarTvT1+IC
        eeIqytwVRLv1h56Hvv+/LrPNIpxcPZNm0b1bEkqYT7zlnj7iTCwz9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T16:14:43Z"
  mac: ENC[AES256_GCM,data:6QuSXX587LfYtBBWxu4ZXw5b8oAqE4Zd3wLZmCWlpzIo72UV6I3PVzrOchZqLft+F+pH/B0M8shTNBIYK8KrlfOlszBifyc4r5WWhVhJPqd+pBxVSI/d1t77shNof3kSu5ZQR5Rbo7moHX9tjlgbLfIZ2Pmtfd/+2uSR0bALBDE=,iv:KqYLZEVOxc9CLoWkCKfNmHBmDcBLUFv1fTs420bzpjE=,tag:bOyQvqRB9zwU5teXtQr1Ew==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
