apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-postgres-credentials
  namespace: database
stringData:
  username: ENC[AES256_GCM,data:NY5MN3DxZqC+TA==,iv:MltolJduN3Sf4HSOn/hviUgShmj98BRXcUTlFxA7tDg=,tag:KhfdEOwIOVkgINSNI5Q2wQ==,type:str]
  password: ENC[AES256_GCM,data:rkPRJALB76O1jmTNXvjjbxZb7PxXZODmV2Zdi8X/zDe4cpVsvQAGAGbqnMG1jmIiNOcfHns14JvEoYDPHio1LA==,iv:CVOH8puoDvWVn6avbX+uhLsvFHshfVaTT20c6B5TgOM=,tag:vPTYIxbaXXJY6MPX4YgUPg==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcThRVFdQQzVpUWFQWnpC
        bzJlNFJWY01DbExGY1hWTE1WdndxQTUxQ0ZzCis4Z0Fad3Y1eWlVUi9Pa1Jqb0c0
        dUNGVTBySW53NGRoS3JqWG1JMTQzNlEKLS0tIGpCVm1YNUhOU3FuUzJVUStBK3VN
        SWtSNzAvUkJsVVlnSzU2OW51TGRpSTQKS5+rqdXlxffMUjWJzjwgt7j1por9+HZs
        PDawF5ixWeTkOcZzD2FyLLpNG1dqiYJ7utiFkdA6ZE4hgooz9RnZUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T16:14:33Z"
  mac: ENC[AES256_GCM,data:88K/906sPd3lu+WY7GHt0x2UGic2eslpK7RtPOS960rLLm7e481J7W/ju8CFVCG4aWC1JOgSpwSSnBTf0yOAYzJJJkkJ9h9czrLJZCdQTCNwWrikaWBrz+oTTuOTf/I4SGvu9hxKOr/lScaV2uoToU5ebte/c6xuR5TfskJiehI=,iv:Id2jG6qro2Uad6wfElr8H6xe34+uxj81BdY1kp0rPXw=,tag:y98egT8XHwoGKdxoV3ZX/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
