apiVersion: v1
kind: Secret
metadata:
    name: tranga-postgres-credentials
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:y3xPytX+,iv:F1n4mhOtdGQVZJNT1ooL58dwqe1o24IrSNxOJ0+vg0w=,tag:0WldYMKOyMp7o8PG19EZ0w==,type:str]
    password: ENC[AES256_GCM,data:CZHl5XnYSfZ/txb7UKnwtcC8aJ6j22Me7UBKlAqyE0CvQ/54eD/lweSb0YMdSErlHqtdUNqruMrK6b4G2Kep3A==,iv:GVMc23QBhzgZucUaIuFV8XCkzavo4EHRjEqKSztYRIU=,tag:GBkpsPfBcmPOPxbYOOcYTw==,type:str]
sops:
    age:
        - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Yms1MHV1V3l1RmNzVjhz
            VVJmWEFKSGRvL29ISjF4Y2gwUjdrOExoWkVRCmRucHhzckdBQXlSdS9KZUdNTFk5
            a0N0Z2JqSEJIeWNGZ0RYTmZ3YnpLR1kKLS0tIGo5YTFXUnpRUTNPSGtmMFZmZ2R6
            K2xmTWYza0xTZlBJcmFUOUpCTTZQNmsKVFuQODBQpGMnEsqOOaoskSqxSYl0GBCg
            Evfd1ndIMwZbkcI4WboQO0Y7ywNecRHWLGsN8G4CeNBaNrM9OiHVdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T23:51:52Z"
    mac: ENC[AES256_GCM,data:qse0xDaZDJ8JybhQA+ju9KfIBvlxcs9IcsnoYVhMsJieYhSOY7E99CL4h822i8yxcXA+JFPLiAfjk2av0PssSCooDNNqwip3WDUozxBr2f5ZcNWVsOrhuwTPUSk2yG+hW+WMobB0GvmXEpzIm6wAlHtNyPX8FZkNQLpNt0+JFMU=,iv:UTBZpPAuI/QBETKespWAQKe2kxsX4Q08yj1vCU/mE/c=,tag:rErlXUw1IDg8Ay45prkEjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
