apiVersion: v1
kind: Secret
metadata:
  name: tranga-postgres-credentials
  namespace: database
stringData:
  username: ENC[AES256_GCM,data:y3xPytX+,iv:F1n4mhOtdGQVZJNT1ooL58dwqe1o24IrSNxOJ0+vg0w=,tag:0WldYMKOyMp7o8PG19EZ0w==,type:str]
  password: ENC[AES256_GCM,data:cml15lQnYGRdJZanfbq/9h4KvJBeJ/xu1Kqzdt8nDkX2RXk57DksHGbgt/ES6qn2fbRY22gWJc06riJcfIwb+Q==,iv:TDJEBnLK4EiVhC2Xq9V/7OYMVpKLvERJogpbMuWRxhA=,tag:WO5mM16y/zHavZiqIx7DKQ==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Yms1MHV1V3l1RmNzVjhz
        VVJmWEFKSGRvL29ISjF4Y2gwUjdrOExoWkVRCmRucHhzckdBQXlSdS9KZUdNTFk5
        a0N0Z2JqSEJIeWNGZ0RYTmZ3YnpLR1kKLS0tIGo5YTFXUnpRUTNPSGtmMFZmZ2R6
        K2xmTWYza0xTZlBJcmFUOUpCTTZQNmsKVFuQODBQpGMnEsqOOaoskSqxSYl0GBCg
        Evfd1ndIMwZbkcI4WboQO0Y7ywNecRHWLGsN8G4CeNBaNrM9OiHVdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T22:29:26Z"
  mac: ENC[AES256_GCM,data:S1/tNZrX4MAxKM/YwinJc2xdUa/DXPdbgnaZRD+R+TgwJVO5jIn0C55YoivUx/Lq9/1AZ5IQ0m4rTS4qUmVbdqK+X409MzKJ0Fuqpmy3XqD/lyTWO2DpbbHhYrkIYCsRjbMv42G+IqYqg7tqMFqhP+PoZw+tI0X9wYnva9cindE=,iv:XWpbgFqKwto2qff9l8QA1dY+H3Gs6Qou+q6j7SlG5Dg=,tag:oIUqTCDovkopi7T0cp3rhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
