apiVersion: v1
kind: Secret
metadata:
  name: gluetun-env
  namespace: yarr
type: Opaque
stringData:
  TZ: ENC[AES256_GCM,data:aIBvVJ2jNHhhR67SXMeU,iv:J1Gj4EIt0ugxOFbYm/Y8+d0Wx/DfY15EqFGjveLU60k=,tag:Is4IvPIH7CkL5eQjVivhPA==,type:str]
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:aimm1OeN,iv:g17Wgb8yCP5oYzLY+DAtMkoPBEwN571UNysgp7HGEIg=,tag:v9aNWQcZhASj1xv6aEZX0g==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:U6LAsZROXkSV,iv:dhsoJ/x8W0ON7dS5YCgLYKx+XEe6HFCZl5DpO83x9pM=,tag:2E5Rf5/FJP+5doATPMcnoA==,type:str]
  #ENC[AES256_GCM,data:uxMut8uc0L9TvPJwfDKGpdRQotw319TEb/1asBKYygLFywGE,iv:Ymnj9+ldKoIh5rgXn2NJYNI4TgnOHjtcJVDKT9dmQLA=,tag:oD9BQmntspsOf9eb2Fik4A==,type:comment]
  WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:0kmF1R4Z/KWvw5yM,iv:nKTtsqyWa9f7Y0SbIfEDwXuMVU+t1OZctMWrpCy9P+M=,tag:bnXj55xCtWMclt2yiCXUSg==,type:str]
  WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:GFm2tRY=,iv:YxBfLYDWnHQjEM8LL9qRDEXR2c32zRX7JVTpClcsr8w=,tag:cbeYQmFhVNGL6zaGfoh6fQ==,type:str]
  #ENC[AES256_GCM,data:fngNzw5Rzw2M+pD4E7zEDc3CqTqFVsSPOBLbDA+rPzhrRYhZKqoeXBPhoUI307rHc+xMNaueAj1U5OLrVOhw9xXw,iv:BpO2wk0NUWb2l/89BL3UPl9klHQ8h0zoC3SoNbga8Ao=,tag:FPVs+Q8oqNDf0gdNumixcA==,type:comment]
  WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:93t/hFrgGZz1iL0AVRLqmoIcNsPqGij7S3Ju01fWZqHBzSUNR+hJjnNRq4s=,iv:A9fvreUfLj6t39RSHdsZsn4e+AVB1g9Ve3bk2LyYNNk=,tag:aR9PY8wY+vw/IcYPcSITlg==,type:str]
  #ENC[AES256_GCM,data:seCHEueRbbtsi7dBDh7089GKTD5tGwUQOqPzWqCmWlzzIdqzqYBdsfLrvRBnYqjuQP+SpEkPQBw6rMWzWUjTI0xu9g==,iv:aWwNsADYRTx8exW30ayn2lcGNxZY2x552AK7MB2WfBM=,tag:1IBSeLWv5d8475VPV7swhA==,type:comment]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:qUd4JtPIBZIuPFJ6lzkXNjXJ/klKaTy9BFr4QrvjXjjeje4u9sDNgwvVMnQ=,iv:/3xB6rMUA6VLsODv+DeSKbalr4rNbRMNr3QV9MXSsjk=,tag:+N+MqGghomyic0CV37qQNw==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Ivo6UuTFihBxk3A=,iv:OACIRau3oFmptEGOivArnu7g6EpIi0gJqTRTUWl6lu8=,tag:BPBF9bJuwnsswXxq4usTIg==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbi9xWUNnSThveGZnVFhK
        VXdZbTBFZDFoYkR6a2VBaU9YSUwrOHZ1a2lJCkg0S2h5aG1ISDUwbXFQWVUwR0Rz
        L2hSNGV5cHBTaG01SFNEc2ZIK2JCTkUKLS0tIGw2aG1NWm1iQVVKUHdYUE1aL0J2
        R0dHeEJxaW9WSDhHandXd3lNTmRKZ2sKimfh0DqS9VbLPHUw5XNzUV24X+pGvSal
        y7BCK5zqUj5C5Nsmd2A6P6tzVQc5qPrJHxB4nDS30+wSHkrnQ9X7Mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T22:36:43Z"
  mac: ENC[AES256_GCM,data:vSTKhQzTlQrnG+674LKXz+y0+QZIZinu7uBkzqrpuSrVrwyNZmOdkfpnqTFZbauqLzQIQXHhx3AYwIqjz9xQFosGNhfLPfbAxGic+UP8nEHwhhpG/INRHRQwNN1lCNXKQ/h6TC3eqJh3r6KBGlU9isYzZbW/K4d+wp7KbRKkFNg=,iv:p/x62POxNadG6zDhxRhJnvU6NKY8xCUPjnBoMv/5G5g=,tag:m4Ps/5qz/uUu6sTmEMg4xw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
