---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jellyfin
  namespace: yarr
spec:
  interval: 1440m
  url: https://jellyfin.github.io/jellyfin-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yarr
  namespace: yarr
spec:
  interval: 30m
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: v1
              kind: PersistentVolumeClaim
              metadata:
                labels:
                  velero-backup: "true"
                annotations:
                  velero.io/csi-volumesnapshot-class: rook-ceph-snapshot
                name: yarr-jellyfin-config
  chart:
    spec:
      chart: jellyfin
      version: ">= 2.7.0 < 2.8.0"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: yarr
      interval: 1m
  values:
    deploymentStrategy:
      type: Recreate
    labels:
      velero-backup: "true"
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: homelab-internal
      hosts:
        - host: "${jellyfin_hostname}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "${jellyfin_hostname}"
          secretName: jellyfin-tls
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    persistence:
      config:
        enabled: true
        storageClass: rook-ceph-retain
        annotations:
          velero.io/csi-volumesnapshot-class: rook-ceph-snapshot
      media:
        enabled: false
    podSecurityContext:
      # fsGroupChangePolicy: OnRootMismatch
      fsGroup: ${groupId}
      # runAsNonRoot: true
    securityContext:
      runAsUser: ${userId}
      runAsGroup: ${groupId}
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        # add:
        #   - SYS_ADMIN
        drop:
          - ALL
      readOnlyRootFilesystem: false
      privileged: false
    tolerations:
      - key: nvidia.com/gpu.count
        operator: Exists
        effect: NoSchedule
    volumeMounts:
      - name: multimedia
        mountPath: /multimedia
    volumes:
      - name: multimedia
        persistentVolumeClaim:
          claimName: multimedia
