apiVersion: v1
kind: Secret
metadata:
  name: harbor-secrets
  namespace: harbor
stringData:
  secretKey: ENC[AES256_GCM,data:QabsdY6Si3oBxTWnkeZ1eA==,iv:lgGmCH6NkGRZ+/FFrpgIIagL6fNvDr69NOUXWbvjOF8=,tag:5uZArFnCcv0TkdaU4uTeqg==,type:str]
  REDIS_USERNAME: ENC[AES256_GCM,data:bX2PRcWc,iv:wBaUKZ6rAJ3ZWeLrjtg+W94ErpuMQtnZ0r/Iq0KZzvQ=,tag:TSeLnN+R2NzOxT+vxm5kyg==,type:str]
  REDIS_PASSWORD: ENC[AES256_GCM,data:LVLvju7TLe2nGzMw/T5ysjWXCu5imBceGe+a/u/D7oq95bSrRQLkBebohjMMZbrTKj+nul5ek1IVNifWMIFCfA==,iv:o9IgKSadUayIdrddts/Lp2SkPFKu7ChHf3ak2ZL6WIk=,tag:JWJttHZkgg/7Ol717z+F9g==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsakhSd2RkaUhUaUNxVzJq
        OWNiQ1hlOC9ubWwyTkxpNUx3cTkwWjNJWlZBCkRieCtya0tOSTQvVU1odzhDYlBJ
        SzVRQlhwNjllaCtZWmJhQzBSVTRKY1EKLS0tIDE5eDJBSnBGNXI3cFpyaVJnSVVs
        K0dydlJSM1M3bXNGR2VTd3dsQnlQSkkKQSay6Mqv7hj7TaGVVFIiVWiyAGpOY5EB
        s001TGNMV1r55rGqs+eBwvPPpXsc92MMEtR5ZgC0KJi9nVU31DFheg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T18:53:31Z"
  mac: ENC[AES256_GCM,data:I0qwfIfZYK40JqcLa4Ygk+Z2LacCfkg1vbNa2S0Oh2eBzrjbETvwv8Wr9AEi4hHse4ERQXY/P/KKkX61PqHO1BP48d8wvdX35J5NoEIfkTzPabMn7eU2XwTCt86bumCK881JNant0SsAaz+jxOYIYkbHsaikoJiFlJrXk730Vus=,iv:HS7Lu6YVXs7fs485H1l0qnvvYAiSvVKokJqD5OW3+XM=,tag:P31KWXQrvOfRlvKr1NK3bA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
