apiVersion: v1
kind: Secret
metadata:
  name: harbor-s3-creds
  namespace: harbor
stringData:
  REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:pzHSMi0VzDY71QZ9k+BO8dHpPMj+eFHCljo=,iv:3rilErn+rVSQwLQKNX4CpuIy194mOTKcbS+8jmbtiWI=,tag:Tw1/bVLK5SqRUXwd6q7ubA==,type:str]
  REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:dSZWbPIyIoUAhdIHMwlbHp65N9+TDCi4KPWoCl/o3vACtlnjUPx8+nLCH7xb25yMiblCxBKnKzsAxMpAsfy7wA==,iv:JFxs8nQt+GY5+zQe8wW/FI7F7hDVzILV2C4nUMY7ats=,tag:po9hp0u9IREhhY9ts5Clng==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTys4UkxhbkpOelF0Wnk5
        dGFDdEd3R04wUGtJQ0E0TDdIdjFWNjhyNmxNClZER3o0amN2cjA2R21nK1FWUldn
        dzkvQXFaZ3I0c3ZGVzZWelhOMEpxTWMKLS0tIEFzbWZwWTRGdm9oT0lFWFArRTNC
        elNzR3lOT0FrRGxJUUhPVjdKT1RJOEUKv3pPchS2aRvWep7mRy/aT2PJlFAyQypc
        mdgNCiFITAoJEpwfEUimaGJhBw4bRRw+t+31uNwWhNpsjig1qo371w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T18:53:23Z"
  mac: ENC[AES256_GCM,data:PJkg3dFTfPKb3IEOenRKeou7nb0IwZWXO26KQ/ZwfqqYVdMhzWRqPP+R1msRakEz7Z3DwLHFc5R6cSS5ESp6sTzQbBEQjg2TVe1IegwG7TWuzlDxiZFdfxozkphB5+IcrrM3UF51XgWmFFKQNakSaNIDh+jEEXb/+xrQZ12bxIw=,iv:ZzTimO7oiviMINUY1YRTKPoxKBc1dYVS8DgUCQsdc8U=,tag:e0tT6iAMXaVsNfvNMZ/SIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
