apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin-creds
  namespace: harbor
stringData:
  HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:MFaY+Di28SartQoALZLJ,iv:1LcHYVbudp49hd+Ssphf6Nznur7Q0bN/2+SSGJ9QTVo=,tag:n054IbRBNQh63lPkwGMUvw==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL1ordlpOcU9ZUDluZXBU
        bENLQWxxc3ZjUGJ4RlI3bUdjdEtEMTFIR1RFCkdBZDZsdWZ6QktpUnN2MmZlV2NO
        eHlLaVA2ZUx3Y08vdHpkZExXS3FHMTgKLS0tIGc4aVJXOEZKZElCM3dPYU83OHht
        d3JJNUR3b0VMbklobE9HZGdXS2RVRm8KWfBX+v0hGQzIWv3920wacbyRofSntRJj
        uDTn5r532uEna3u8HbaCEpIW1PA/0OhpAGf9G1O2E4eShznW7AisSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T18:53:16Z"
  mac: ENC[AES256_GCM,data:2DYYA6aG6WORyLzBdNusduubWk3INDMg1TFUjW7XkglIb/ndKa2493JIZXT904g/pzto69wy2t1AkQVzKH9DRXl+28K6soRggeHZEajMC/GvDYS503g8igySouVgxE6ztsXGnm1AG3E1VeAkMrGVwb+CVH5L7pHsAVvbkkNE88I=,iv:ZPBuzHEpnNOPUcjzq/NF5qvw19nfaMk94bcOqUEJnpI=,tag:kOu2L58yDCW2kKFyixFE2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
