apiVersion: v1
kind: Secret
metadata:
  name: harbor-postgres-credentials
  namespace: harbor
stringData:
  username: ENC[AES256_GCM,data:Iq/5ZgWl,iv:qqTrkKaoL3k4ZEUTdoZh/Ty2qOCzuLMvkjrV/aUD/RM=,tag:0CcvYOxy3G7f5kqaCoafJg==,type:str]
  password: ENC[AES256_GCM,data:/64IlBo8t8fs6zRXcVjgtbq4YGX3fVqAspgQMtgS8czUXuvS3OgZzEcZiIV859avkCHbOfZiuYlTr7Gt5aa0LA==,iv:P+hlmcjuxsn/80dKukiZ8Z14t6dlGYRs1gOux5DWKwk=,tag:H7A/9xlg/ff5lfCMzHeKOA==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cVAzYm9zbmV0OTYzdGtD
        K1lIblI1dGFSRzdPSlZCem5ZYXJpVFNmaTFVClBjeCtpTVUzWDRKai9UU0pLT1Mx
        WmxOd1NhMlh3U2NiQ1V3eDduSnpuSzQKLS0tIFpWL01vOFlMd0szWmt1WE9zMklt
        TE9QT2hZamx0NmtIclB2N2tkb2JselUKe6unuWOlnt1X2tcm1o8POdzZIfNq8m6+
        qXZQlq2j3SsgayMD/g+vJUlIwOGBjTWwBeudKXsoMmzBtwPEyqXMYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T18:53:41Z"
  mac: ENC[AES256_GCM,data:VRd0XWikE4GKh50M4EhogSQdkJDhHUQDX07FBIMYFcQ1jfP1zX9sS9cAdmvOpFE9IUFIfeYNPaU0MMPQ5dFq9gLmYMQawOSKz/ph1ea+/LLd3f0f5+pIdhUJNY0IXXtCXDpe+VIvSMxvNT4ZkdmzPEpjNoWb9VgwYiiSS4aPdOg=,iv:6oxchi1hYrzcake1Y2Vuo61/dQLAxGHCTkHEa2ZTwSw=,tag:8SXe+iK1ElnaxSUZpCurCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
