apiVersion: v1
kind: Secret
metadata:
  name: cnpg-harbor-pg-backup-creds
  namespace: harbor
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:dV4Qm80i6iY1lcO7rkS0FJUvdHtXbRqpZhs=,iv:QqYyP0YOZu0G69+0MC71XcXXfC+pGZvUNFcYuWJIPac=,tag:ObmsNEeYkoJUqL2dyKusVA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:mzINpXiVAq/UBeUfX9iP0x+c0zJ47jG81iwnz0fa3PXiiIbeulxycPu6a5ME86P6tThkByA3FLgKW248S8fGQA==,iv:ZDbdpUxCGMfeWD5AFvzHOfL4dwTWu9RKdClXe7FpSr8=,tag:zDvVuTiGjV+Uq24zxfkLTg==,type:str]
  region: ENC[AES256_GCM,data:HbVd+e1Q,iv:yMMlb6OM2Cb9UEXgDqs0W0fiIy0P7bHrQKwNaYc7xwQ=,tag:+j/tjBl1tokNq5KgQaOOIg==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN2RJdnFLQnJLdktGQ1NW
        SXNLdWtBNzF6R3pRSFE2ck5KUWRoVnNQY3g4Ck16dkh3cDM5ZHJ5VldUZ0hPQXdI
        QTdMcy8zc2ZTaXcrazc1YXZRVkJaVW8KLS0tIG5xb2tKVjJEM1hkKzcvUlZRSG8z
        MmZRcHdvV1ExNUVZV0V4djcxMWVSUGcK/qJljhLzt/W7mmOSo43wQORT6WrZntNq
        K9qpxeeJ4WDqESDpy17Augu4WlV1sIrrEs+6ylkGarLh5xUzEs8nJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T18:53:49Z"
  mac: ENC[AES256_GCM,data:IbLGiaZUoP5WCDL27BLV4jCvC8TalybnpBvOWKNYqiy/uEOafexgyoDIYqPFjL/coUADRzKv20CgqwIZDJGuZWds2rJkd5LsCBLNQX6M9mhE4ip4DNO+ESq6fjxU2bporoaMF9G+KQzLvZEM60PL3mNFq4COUsSFeqOnljY92Vo=,iv:KbZSnZQoqWuWnW8ttdCUT9JFm9ErLa3VrMNzbwD1S5c=,tag:FcFEzsPDR+PIfeabLHI//w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
