apiVersion: v1
kind: Secret
metadata:
  name: harbor-valkey-users
  namespace: harbor
type: Opaque
stringData:
  default: ENC[AES256_GCM,data:Y33sQe9soi83qtKnMve1DidkuALEX1LuERzb+ScZFTGGEwcUOW2lTCdtR4KD/nxljS3ngsVfqiRSAmaEHM0vyA==,iv:EQw1q3leY8nu+5DPXpTwN7NotdGF207mWohdHfFhoGw=,tag:uVs7t7FttaDgneg1nys3dw==,type:str]
  harbor: ENC[AES256_GCM,data:2qQNd44CV1gXzYBLqkGbmkgLXIReQxHLh/xO8le1fkrYRC1sBkKZ7D05CgCrIy9ao1qKKFXLSqUz8xKJqCrVyw==,iv:osvxhovfBeOW88sJ1g4EyVWb/Wool2Y/TDj7tqFIMj0=,tag:TE3yNtHGzIJ5fT1gEnMOsw==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRk4wRFVyZWl6aTZ1cElM
        enNkRGZ6ZWZabnBXbUlxNlUrZCt4VU9jWnd3Cms1T1E0aUt2ZzJZUFBBcDFORERz
        bTV3NitKTDJhMW5sMXJ1MTlPWmpqR0kKLS0tIEFZWEVlWkR2cWcwTGM4dS8yN0lS
        dzlDUTdad2M0c2VrR2p0NTN0Q1ZGcVEK9og7LHon4yLiTyATpsXhkOgqibm9mV40
        Ir+7i15SkXdTySwdy4r+7isTFHx69TFtuA6wEQkb5XS4C7Yq0xJZRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T18:54:02Z"
  mac: ENC[AES256_GCM,data:P63f2DdNNHYknV2gSNzX3JnUiycPJ6plsVAChp6UeA41FPzEUsDnhBqhCRJBhvgx9sb7GvTVmO1D70ZyYCs1pDNZmOBNYMLH8LSSOPEMQyy1TdNtOAoS/SjUXDaxKmrL8kg2MG3It6l2I5+mhWI88vzakJLY0KfeLeyYst8ibEI=,iv:GDQeg6Jgwui/g6bNIcBjcgOXk8WTlZzUrIcHks9465E=,tag:VbLz6Z3dXsE2vFbESVJTuA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
