subdomain: ENC[AES256_GCM,data:Djl+/CBfy/lfxYxnb2wWPM1kug==,iv:5kgA3ZDDqUomU6Etp8ISUBCCLuCoWQbleUenfQv0pu0=,tag:KQ1QPIeO3M8H7XWbHXrlkQ==,type:str]
gateway: ENC[AES256_GCM,data:cfjzldMpvoCiI1xp,iv:f+I4+Ut2nuDvwYAoKm895bu5QlMrmQzqE1fxHiUnoRg=,tag:vdQE7HRSts0m1RmU6MCL8A==,type:str]
cidr: ENC[AES256_GCM,data:IlxyRHVIyNq0/ygDLkJe,iv:5lFlci5X8ewTZiXTBM6N8m2A2NqzBsH4UhC8cxVp6p4=,tag:J31cbY/xU7SVi7FowHACmg==,type:str]
sops:
  age:
    - recipient: age195m7v6w6lce8knleuc9juqwklj56vjflng64q60eh90yrfpsfyjs222pls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdkZJMkxEMERUQ1E5OGRO
        MXFMcWpPUHppSDlIOFpGYmxDelhlWENWOUhJCi9BMXlnMmpFYkVUV0xBTVp4UHZk
        MlJGSThsamJsQjJxT2J4NGxmZDl4L3cKLS0tIDJMUWFxTHNnUk5hUFZwUEhIYVdL
        MEkrV00weS9XSml2Vkt5Y3VJaWo0dTAKZVikX4Ygqe54+sHd1UTAma2ZB8hlUqIm
        ZQxu+8jZrW9Cyn5saPtjmmvdxmIPQsDIxKYp4PlkOh/lY3SkUjBn6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T02:09:35Z"
  mac: ENC[AES256_GCM,data:/yeInJAxYq1j4ezQkztMr1Sor2Q27wPRhS0df05sgiHTJG7wiN0L3WZ55afe7irrOWKIuoNTUoni0t6dDqieVj3qzIr6PPUa3gcKm2DrcWZ9/supU8l+ikTkwpLAelbnVNtR33hLt7ANGhUzRArKuvnEFIf+fzvFoxI1p2jYodg=,iv:RO7IayX0Z3jOVepnIdis9IVpmlorMdpQz3Z3k+8vDNM=,tag:nUUO4DP7p1Rh1sjSPOWY/g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
