apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # generic-device-plugin
  - https://raw.githubusercontent.com/squat/generic-device-plugin/main/manifests/generic-device-plugin.yaml
  - https://raw.githubusercontent.com/squat/generic-device-plugin/main/manifests/podmonitor.yaml
