---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 1440m
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage
  ref:
    semver: "v2.2.*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 5m
  chart:
    spec:
      chart: ./script/helm/garage
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
      interval: 1m
  values:
    deployment:
      replicaCount: 1
    extraVolumeMounts:
      - name: garage
        mountPath: /garage-storage
    extraVolumes:
      - name: garage
        persistentVolumeClaim:
          claimName: garage
    garage:
      replicationFactor: "1"
      garageTomlString: |-
        metadata_dir = "/garage-storage/meta"
        data_dir = "/garage-storage/data"

        db_engine = "lmdb"

        block_size = 1048576

        replication_factor = 1
        consistency_mode = "consistent"

        compression_level = 1

        rpc_bind_addr = "[::]:3901"
        # rpc_secret will be populated by the init container from a k8s secret object
        rpc_secret = "__RPC_SECRET_REPLACE__"

        bootstrap_peers = []

        [kubernetes_discovery]
        namespace = "garage"
        service_name = "release-name-garage"
        skip_crd = false

        [s3_api]
        s3_region = "garage"
        api_bind_addr = "[::]:3900"
        root_domain = ".${s3_api_hostname}"

        [s3_web]
        bind_addr = "[::]:3902"
        root_domain = ".${s3_web_hostname}"
        index = "index.html"

        [admin]
        api_bind_addr = "[::]:3903"
    ingress:
      s3:
        api:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 500m
            cert-manager.io/cluster-issuer: homelab-internal
          hosts:
            - host: ${s3_api_hostname}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "${s3_api_hostname}"
              secretName: garage-api-tls
        web:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 500m
            cert-manager.io/cluster-issuer: homelab-internal
          hosts:
            - host: ${s3_web_hostname}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "${s3_web_hostname}"
              secretName: garage-web-tls
    monitoring:
      metrics:
        enabled: true
      serviceMonitor:
        enabled: true
    persistence:
      enabled: false
    podSecurityContext:
      fsGroup: ${groupId}
      runAsGroup: ${groupId}
      runAsUser: ${userId}
