apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # gateway-api-experimental
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.4.1/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
