---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: admin
data:
  servers.json: |
    {
        "Servers": {
          "1": {
            "Name": "pg00",
            "Group": "k8s00",
            "Port": 5432,
            "Username": "postgres",
            "Host": "pg00-rw.database",
            "SSLMode": "prefer",
            "MaintenanceDB": "postgres"
          },
          "2": {
            "Name": "immich-pg",
            "Group": "k8s00",
            "Port": 5432,
            "Username": "immich",
            "Host": "immich-pg-rw.immich",
            "SSLMode": "prefer",
            "MaintenanceDB": "postgres"
          },
          "3": {
            "Name": "harbor-pg",
            "Group": "k8s00",
            "Port": 5432,
            "Username": "harbor",
            "Host": "harbor-pg-rw.harbor",
            "SSLMode": "prefer",
            "MaintenanceDB": "postgres"
          }
        }
    }
  config_distro.py: |
    CA_FILE = '/etc/ssl/certs/ca-certificates.crt'
    LOG_FILE = '/dev/null'
    HELP_PATH = '../../docs'
    DEFAULT_BINARY_PATHS = {
            'pg': '/usr/local/pgsql-18',
            'pg-18': '/usr/local/pgsql-18',
            'pg-17': '/usr/local/pgsql-17',
            'pg-16': '/usr/local/pgsql-16',
            'pg-15': '/usr/local/pgsql-15',
            'pg-14': '/usr/local/pgsql-14',
            'pg-13': '/usr/local/pgsql-13'
    }
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-http
  namespace: admin
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app: pgadmin
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  namespace: admin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: rook-ceph-retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: admin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 5050
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:9.12
          imagePullPolicy: Always
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-creds
                  key: pgadmin-username
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-creds
                  key: pgadmin-password
            - name: PGADMIN_DISABLE_POSTFIX
              value: "true"
            - name: PGADMIN_LISTEN_PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
            - name: pgadmin-config
              mountPath: /pgadmin4/config_distro.py
              subPath: config_distro.py
            - name: tmp
              mountPath: /tmp
          securityContext:
            # capabilities:
            #   drop:
            #   - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 5050
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: pgadmin-config
          configMap:
            name: pgadmin-config
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-data
        - name: tmp
          emptyDir: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: homelab-internal
  name: pgadmin-ingress
  namespace: admin
spec:
  ingressClassName: nginx
  rules:
    - host: pgadmin.${serviceDomain}
      http:
        paths:
          - backend:
              service:
                name: pgadmin-http
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - pgadmin.${serviceDomain}
      secretName: pgadmin.${serviceDomain}-tls
