---
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-gpu
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvdp
  namespace: nvidia-gpu
spec:
  interval: 1440m
  url: https://nvidia.github.io/k8s-device-plugin
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-gpu
spec:
  interval: 1440m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: ">= 0.17.3 < 0.18.0"
      sourceRef:
        kind: HelmRepository
        name: nvdp
      interval: 60m
  values:
    runtimeClassName: nvidia
    gfd:
      enabled: true
